export const REQUEST_PERIOD = 'REQUEST_PERIOD';
export const REQUEST_PERIOD_SUCCESS = 'REQUEST_PERIOD_SUCCESS';
export const REQUEST_PERIOD_SUCCESS_EMPTY = 'REQUEST_PERIOD_SUCCESS_EMPTY';
export const REQUEST_PERIOD_FAILED = 'REQUEST_PERIOD_FAILED';
// List
export const REQUEST_PERIODS = 'REQUEST_PERIODS';
export const REQUEST_PERIODS_SUCCESS = 'REQUEST_PERIODS_SUCCESS';
export const REQUEST_PERIODS_SUCCESS_EMPTY = 'REQUEST_PERIODS_SUCCESS_EMPTY';
export const REQUEST_PERIODS_FAILED = 'REQUEST_PERIODS_FAILED';
// List eventualities
export const REQUEST_PERIODS_EVENTUALITIES = 'REQUEST_PERIODS_EVENTUALITIES';
export const REQUEST_PERIODS_EVENTUALITIES_SUCCESS = 'REQUEST_PERIODS_EVENTUALITIES_SUCCESS';
export const REQUEST_PERIODS_EVENTUALITIES_SUCCESS_EMPTY = 'REQUEST_PERIODS_EVENTUALITIES_SUCCESS_EMPTY';
export const REQUEST_PERIODS_EVENTUALITIES_FAILED = 'REQUEST_PERIODS_EVENTUALITIES_FAILED';
// List liquidation
export const REQUEST_PERIODS_LIQUIDATION = 'REQUEST_PERIODS_LIQUIDATION';
export const REQUEST_PERIODS_LIQUIDATION_SUCCESS = 'REQUEST_PERIODS_LIQUIDATION_SUCCESS';
export const REQUEST_PERIODS_LIQUIDATION_SUCCESS_EMPTY = 'REQUEST_PERIODS_LIQUIDATION_SUCCESS_EMPTY';
export const REQUEST_PERIODS_LIQUIDATION_FAILED = 'REQUEST_PERIODS_LIQUIDATION_FAILED';
// Get By Id
export const REQUEST_PERIOD_EDIT = 'REQUEST_PERIOD_EDIT';
export const REQUEST_PERIOD_EDIT_SUCCESS = 'REQUEST_PERIOD_EDIT_SUCCESS';
export const REQUEST_PERIOD_EDIT_SUCCESS_EMPTY = 'REQUEST_PERIOD_EDIT_SUCCESS_EMPTY';
export const REQUEST_PERIOD_EDIT_FAILED = 'REQUEST_PERIOD_EDIT_FAILED';
// Save
export const SAVE_PERIOD = 'SAVE_PERIOD';
export const SAVE_PERIOD_SUCCESS = 'SAVE_PERIOD_SUCCESS';
export const SAVE_PERIOD_FAILED = 'SAVE_PERIOD_FAILED';
// Remove
export const REMOVE_PERIOD = 'REMOVE_PERIOD';
export const REMOVE_PERIOD_SUCCESS = 'REMOVE_PERIOD_SUCCESS';
export const REMOVE_PERIOD_FAILED = 'REMOVE_PERIOD_FAILED';
// empty edit
export const EMPTY_PERIOD_EDIT = 'EMPTY_PERIOD_EDIT';
