// Request All List
export const REQUEST_ALL_EXCLUSION = 'REQUEST_ALL_EXCLUSION';
export const REQUEST_ALL_EXCLUSION_SUCCESS = 'REQUEST_ALL_EXCLUSION_SUCCESS';
export const REQUEST_ALL_EXCLUSION_SUCCESS_EMPTY = 'REQUEST_ALL_EXCLUSION_SUCCESS_EMPTY';
export const REQUEST_ALL_EXCLUSION_FAILED = 'REQUEST_ALL_EXCLUSION_FAILED';
// Request Family Exclusion
export const REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION = 'REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION';
export const REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_SUCCESS = 'REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_SUCCESS';
export const REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_SUCCESS_EMPTY = 'REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_SUCCESS_EMPTY';
export const REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_FAILED = 'REQUEST_FAMILY_VEHICLE_COLUMNS_EXCLUSION_FAILED';
// Post Save or Update
export const SAVE_EXCLUSION = 'SAVE_EXCLUSION';
export const SAVE_EXCLUSION_SUCCESS = 'SAVE_EXCLUSION_SUCCESS';
export const SAVE_EXCLUSION_FAILED = 'SAVE_EXCLUSION_FAILED';
