// Request List Parameters
export const REQUEST_PARAMETERS = 'REQUEST_PARAMETERS';
export const REQUEST_PARAMETERS_SUCCESS = 'REQUEST_PARAMETERS_SUCCESS';
export const REQUEST_PARAMETERS_SUCCESS_EMPTY = 'REQUEST_PARAMETERS_SUCCESS_EMPTY';
export const REQUEST_PARAMETERS_FAILED = 'REQUEST_PARAMETERS_FAILED';
// Update
export const UPDATE_PARAMETERS = 'UPDATE_PARAMETERS';
export const UPDATE_PARAMETERS_SUCCESS = 'UPDATE_PARAMETERS_SUCCESS';
export const UPDATE_PARAMETERS_FAILED = 'UPDATE_PARAMETERS_FAILED';
