export const REQUEST_CONSOLIDATED_LIST = 'REQUEST_CONSOLIDATED_LIST';
export const REQUEST_CONSOLIDATED_LIST_SUCCESS = 'REQUEST_CONSOLIDATED_LIST_SUCCESS';
export const REQUEST_CONSOLIDATED_LIST_EMPTY = 'REQUEST_CONSOLIDATED_LIST_EMPTY';
export const REQUEST_CONSOLIDATED_LIST_FAILED = 'REQUEST_CONSOLIDATED_LIST_FAILED';
export const REQUEST_CONSOLIDATED_SAVE = 'REQUEST_CONSOLIDATED_SAVE';
export const REQUEST_CONSOLIDATED_SAVE_SUCCESS = 'REQUEST_CONSOLIDATED_SAVE_SUCCESS';
export const REQUEST_CONSOLIDATED_SAVE_FAILED = 'REQUEST_CONSOLIDATED_SAVE_FAILED';
