// Request List Group
export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const REQUEST_GROUPS_SUCCESS = 'REQUEST_GROUPS_SUCCESS';
export const REQUEST_GROUPS_SUCCESS_EMPTY = 'REQUEST_GROUPS_SUCCESS_EMPTY';
export const REQUEST_GROUPS_FAILED = 'REQUEST_GROUPS_FAILED';
// Request DealerShip and edit info
export const REQUEST_DEALERSHIP = 'REQUEST_DEALERSHIP';
export const REQUEST_DEALERSHIP_SUCCESS = 'REQUEST_DEALERSHIP_SUCCESS';
export const REQUEST_DEALERSHIP_SUCCESS_EMPTY = 'REQUEST_DEALERSHIP_SUCCESS_EMPTY';
export const REQUEST_DEALERSHIP_FAILED = 'REQUEST_DEALERSHIP_FAILED';
// Save
export const SAVE_GROUPS = 'SAVE_GROUPS';
export const SAVE_GROUPS_SUCCESS = 'SAVE_GROUPS_SUCCESS';
export const SAVE_GROUPS_FAILED = 'SAVE_GROUPS_FAILED';
// Empty Edit an Create info
export const EMPTY_GROUPS = 'EMPTY_GROUPS';
