// Request List
export const REQUEST_BILLING_CRITERIA = 'REQUEST_BILLING_CRITERIA';
export const REQUEST_BILLING_CRITERIA_SUCCESS = 'REQUEST_BILLING_CRITERIA_SUCCESS';
export const REQUEST_BILLING_CRITERIA_SUCCESS_EMPTY = 'REQUEST_BILLING_CRITERIA_SUCCESS_EMPTY';
export const REQUEST_BILLING_CRITERIA_FAILED = 'REQUEST_BILLING_CRITERIA_FAILED';
// Request All List
export const REQUEST_ALL_BILLING_CRITERIA = 'REQUEST_ALL_BILLING_CRITERIA';
export const REQUEST_ALL_BILLING_CRITERIA_SUCCESS = 'REQUEST_ALL_BILLING_CRITERIA_SUCCESS';
export const REQUEST_ALL_BILLING_CRITERIA_SUCCESS_EMPTY = 'REQUEST_ALL_BILLING_CRITERIA_SUCCESS_EMPTY';
export const REQUEST_ALL_BILLING_CRITERIA_FAILED = 'REQUEST_ALL_BILLING_CRITERIA_FAILED';
// Save BillingCriteriaPeriod
export const SAVE_BILLING_CRITERIA_PERIOD = 'SAVE_BILLING_CRITERIA_PERIOD';
export const SAVE_BILLING_CRITERIA_PERIOD_SUCCESS = 'SAVE_BILLING_CRITERIA_PERIOD_SUCCESS';
export const SAVE_BILLING_CRITERIA_PERIOD_FAILED = 'SAVE_BILLING_CRITERIA_PERIOD_FAILED';
// Request Family Vehicles Billing Criteria
export const REQUEST_FAMILY_VEHICLE = 'REQUEST_FAMILY_VEHICLE';
export const REQUEST_FAMILY_VEHICLE_SUCCESS = 'REQUEST_FAMILY_VEHICLE_SUCCESS';
export const REQUEST_FAMILY_VEHICLE_SUCCESS_EMPTY = 'REQUEST_FAMILY_VEHICLE_SUCCESS_EMPTY';
export const REQUEST_FAMILY_VEHICLE_FAILED = 'REQUEST_FAMILY_VEHICLE_FAILED';
// Post Save or Update
export const SAVE_BILLING_CRITERIA = 'SAVE_BILLING_CRITERIA';
export const SAVE_BILLING_CRITERIA_SUCCESS = 'SAVE_BILLING_CRITERIA_SUCCESS';
export const SAVE_BILLING_CRITERIA_FAILED = 'SAVE_BILLING_CRITERIA_FAILED';
// Empty Edit an Create info
export const EMPTY_BILLING_CRITERIA = 'EMPTY_BILLING_CRITERIA';
