export const REQUEST_PERIOD = 'REQUEST_PERIOD';
export const REQUEST_PERIOD_SUCCESS = 'REQUEST_PERIOD_SUCCESS';
export const REQUEST_PERIOD_SUCCESS_EMPTY = 'REQUEST_PERIOD_SUCCESS_EMPTY';
export const REQUEST_PERIOD_FAILED = 'REQUEST_PERIOD_FAILED';
