export const REQUEST_OBJECTIVE = 'REQUEST_OBJECTIVE';
export const REQUEST_OBJECTIVE_SUCCESS = 'REQUEST_OBJECTIVE_SUCCESS';
export const REQUEST_OBJECTIVE_FAILED = 'REQUEST_OBJECTIVE_FAILED';
export const REQUEST_OBJECTIVE_EMPTY = 'REQUEST_OBJECTIVE_EMPTY';
