// Request All List
export const REQUEST_ALL_ACCOMPLISHMENTS = 'REQUEST_ALL_ACCOMPLISHMENTS';
export const REQUEST_ALL_ACCOMPLISHMENTS_SUCCESS = 'REQUEST_ALL_ACCOMPLISHMENTS_SUCCESS';
export const REQUEST_ALL_ACCOMPLISHMENTS_SUCCESS_EMPTY = 'REQUEST_ALL_ACCOMPLISHMENTS_SUCCESS_EMPTY';
export const REQUEST_ALL_ACCOMPLISHMENTS_FAILED = 'REQUEST_ALL_ACCOMPLISHMENTS_FAILED';
export const REMOVE_ACCOMPLISHMENTS = 'REMOVE_ACCOMPLISHMENTS';
// Items in front
export const ONREMOVE_ITEM_ACCOMPLISHMENTS = 'ONREMOVE_ITEM_ACCOMPLISHMENTS';
export const ONADD_ITEM_ACCOMPLISHMENTS = 'ONADD_ITEM_ACCOMPLISHMENTS';

// Save All List
export const SAVE_ALL_ACCOMPLISHMENTS_SUCCESS = 'SAVE_ALL_ACCOMPLISHMENTS_SUCCESS';
export const SAVE_ALL_ACCOMPLISHMENTS_FAILED = 'SAVE_ALL_ACCOMPLISHMENTS_FAILED';
