// Request All List
export const REQUEST_ALL_RANGES = 'REQUEST_ALL_RANGES';
export const REQUEST_ALL_RANGES_SUCCESS = 'REQUEST_ALL_RANGES_SUCCESS';
export const REQUEST_ALL_RANGES_SUCCESS_EMPTY = 'REQUEST_ALL_RANGES_SUCCESS_EMPTY';
export const REQUEST_ALL_RANGES_FAILED = 'REQUEST_ALL_RANGES_FAILED';

// Items in front
export const ONREMOVE_ITEM_RANGES = 'ONREMOVE_ITEM_RANGES';
export const ONADD_ITEM_RANGES = 'ONADD_ITEM_RANGES';

// Save All List
export const SAVE_ALL_RANGES_SUCCESS = 'SAVE_ALL_RANGES_SUCCESS';
export const SAVE_ALL_RANGES_FAILED = 'SAVE_ALL_RANGES_FAILED';

// Delete Range
export const DELETE_ALL_RANGES_SUCCESS = 'DELETE_ALL_RANGES_SUCCESS';
export const DELETE_ALL_RANGES_FAILED = 'DELETE_ALL_RANGES_FAILED';
