export const REQUEST_NPS_LIST = 'REQUEST_NPS_LIST';
export const REQUEST_NPS_LIST_SUCCESS = 'REQUEST_NPS_LIST_SUCCESS';
export const REQUEST_NPS_LIST_EMPTY = 'REQUEST_NPS_LIST_EMPTY';
export const REQUEST_NPS_LIST_FAILED = 'REQUEST_NPS_LIST_FAILED';
export const REQUEST_NPS_SAVE = 'REQUEST_NPS_SAVE';
export const REQUEST_NPS_SAVE_SUCCESS = 'REQUEST_NPS_SAVE_SUCCESS';
export const REQUEST_NPS_SAVE_FAILED = 'REQUEST_NPS_SAVE_FAILED';
