export const REQUEST_PRE_SETTLEMENT_PROGRESS = 'REQUEST_PRE_SETTLEMENT_PROGRESS';
export const REQUEST_PRE_SETTLEMENT_SUCCESS = 'REQUEST_PRE_SETTLEMENT_SUCCESS';
export const REQUEST_PRE_SETTLEMENT_FAILED = 'REQUEST_PRE_SETTLEMENT_FAILED';
